const LOAD_QUESTIONS = 'LOAD_QUESTIONS';

const ADD_RESPONSE = 'ADD_RESPONSE';

const CLEAR_QUESTIONS = 'CLEAR_QUESTIONS';

const CLEAR_ERROR_MESSAGE = 'CLEAR_ERROR_MESSAGE';

const RENDER_ERROR_MESSAGE = 'RENDER_ERROR_MESSAGE';

export {
  LOAD_QUESTIONS, ADD_RESPONSE, CLEAR_QUESTIONS, CLEAR_ERROR_MESSAGE, RENDER_ERROR_MESSAGE
};
