const ADD_QUESTIONS = "ADD_QUESTIONS";

const UPDATE_GAMESTATE = "UPDATE_GAMESTATE";

const ADD_RESPONSE = "ADD_RESPONSE";

const CLEAR_QUESTIONS = "CLEAR_QUESTIONS";

export { ADD_QUESTIONS, UPDATE_GAMESTATE, ADD_RESPONSE, CLEAR_QUESTIONS }
